const express = require('express')
const router = express.Router()
const control = require('../controllers')
const mid = require('../helpers/middleware')

router.use('/auth/register', control.auth.regist)
router.use('/auth/login', control.auth.login)
router.use('/auth/whoami', mid.mustLogin, control.auth.whoami)
router.use('/auth/change', mid.mustLogin, control.auth.changePassword)
router.use('/user/index', control.user_game.index)
router.use('/user/delete', control.user_game.delete)
router.use('/user-bio/create', control.user_game_biodata.create)
router.use('/user-bio/index', control.user_game_biodata.index)
router.use('/user-bio/update', control.user_game_biodata.update)
router.use('/user-bio/delete', control.user_game_biodata.delete)
router.use('/user-history/create', control.user_game_history.create)
router.use('/user-history/index', control.user_game_history.index)
router.use('/user-history/update', control.user_game_history.update)
router.use('/user-history/delete', control.user_game_history.delete)

module.exports = router